### ISSUE TITLE
Black list

### ISSUE THREAD

**Issue by cathartyc** [AFLdiscord/AFL-Bot#1]
Servirebbe implementare una black list che abbia le seguenti caratteristiche:
- file testuale con le stringhe bandite, nella stessa cartella degli altri file;
- comando per aggiungere stringhe da bandire al file testuale (solo per moderatori) e.g. `\blackadd "pu***na",` che venga eliminato dopo essere stato eseguito;
- condizione che impedisce l'incremento del contatore di messaggi/testo mandati/o qualora il termine appartenesse alla BL;
- eliminazione dei messaggi banditi;
- incremento penalità.

**Comment by Skylake-dev** [comment]
Bisogna anche controllare che le parole bannate non siano presenti in username o nickname dei membri.

**Comment by cathartyc** [comment]
In più va aggiunto un check sul canale in cui viene mandato il messaggio, per evitare di censurare anche canali quali #anarchia.
