### ISSUE TITLE
Cambio nickname

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#10]
Cambiando username due volte di fila è possibile cambiare nickname, controllare on_member_update e on_user_update.

**Comment by Skylake-dev** [comment]
Step per riprodurre
Condizioni di base: utente con nickname uguale all'username (quello di default) per esempio Mario
- cambia username da Mario a Luigi
- il bot si accorge che il nome visualizzato viene cambiato e imposta il nickname a Mario
situazione --> username Luigi  nickname Mario
- rifare la modifica al contrario cambiando username da Luigi a Mario
ESITO ATTESO
il nickname resta Mario
ESITO EFFETTIVO
il nickname viene cambiato dal bot da Mario a Luigi

**Comment by Skylake-dev** [comment]
Sembrerebbe che User.display_name ritorni in ogni caso l'username del membro, non penso sia possibile evitarlo

**Comment by cathartyc** [comment]
La falla, basata sul cambiare username secondo lo schema A-->B-->A, potrebbe essere inconsapevolmente sfruttata da chi, per esempio, decide di cambiare username per prova e poi decide di tornare indietro: non sempre chi si ritrova in questa situazione quindi è punibile.
L'idea per non passare per display_name potrebbe essere quella di salvare il nickname all'ingresso di AFL in un campo nell'elenco aflers.json, e fare check del nickname con quello salvato (quando cambia l'username si impone sempre il nick salvato nel file, senza bisogno di effettuare controlli).

**Comment by Skylake-dev** [comment]
Sarebbe da cambiare anche la logica secondo cui qualcuno viene aggiunto al file aflers.json
attualmente viene aggiunto al primo messaggio in un canale valido, occorre farlo non appena riceve il ruolo afl salvando il nickname in quel momento. Questo permetterebbe eventualmente di consentire cambi di nickname approvati dai mod senza dover cambiare i permessi dei ruoli (comando <setnick ?)

**Comment by cathartyc** [comment]
Esattamente.
In tal modo si può sempre referenziare un membro del server anche se non ha mai scritto un messaggio: non procura molti vantaggi ma rende più flessibili eventuali interventi diretti sul file (correzione numero messaggi, date,...).
Per il comando <setnick possiamo pensare anche alla possibilità di lasciarlo in mano all'utente, aggiungendo un altro campo in aflers.json contenente la data dell'ultimo cambio di nickname, e permetterne il cambiamento solo ogni tot di tempo dall'ultimo cambio (o dopo essere stato ammesso in AFL).

**Comment by Skylake-dev** [comment]
Apro una issue separata per il comando setnick
