### ISSUE TITLE
Votazione delle proposte

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#12]
Affidare al bot il controllo delle votazioni del canale proposte. Per ora controlla solo che le proposte siano votate dai soli aventi diritto. Sarebbe da aggiungere anche:
- controllo del numero di aventi diritto al voto nel momento in cui viene postata una proposta
- a ogni voto aggiunto/rimosso, controllare se la proposta ha raggiunto la maggioranza e agire di conseguenza
- in caso non vengano raggiunti i voti necessari, eliminare la proposta trascorso il tempo di validità
Ogni proposta viene salvata in un file json nel seguente modo:
```
"id_proposta": {
    "timestamp":  timestamp della proposta,
    "total_voters":  numero di aventi diritto a votare la proposta,
    "yes":  voti a favore,
    "no":  voti contrari
}
```

**Comment by Skylake-dev** [comment]
Da chiarire ancora:
- granularità del timestamp
- inserire anche la soglia già calcolata nell'archivio? (per ora il criterio è maggioranza assoluta)
- cosa fare al raggiungimento della soglia (messaggio di avviso? elimino il messaggio? annuncio?)
@cathartyc suggerimenti ben accetti

**Comment by cathartyc** [comment]
> granularità del timestamp

Per fare le cose facilmente direi di mettere un timestamp nudo e crudo. Al limite non andremmo oltre i minuti.

> inserire anche la soglia già calcolata nell'archivio? (per ora il criterio è maggioranza assoluta)

Direi di sì, così al passaggio del sistema a maggioranza relativa sarà più agevole il cambio codice (per ora possiamo impostare la soglia banalmente come la parte intera superiore della metà degli attivi.

> cosa fare al raggiungimento della soglia (messaggio di avviso? elimino il messaggio? annuncio?)

Premessa: con proposta "passata" mi riferisco a quelle proposte che ricevono il numero minimo di voti favorevoli, mentre con proposta "approvata" mi riferisco a quella che è passata e che viene accettata da un AFL M.

L'idea che mi immaginavo era quella di avere:
- Permesso di voto solo fino a proposta passata (ulteriori voti andrebbero rimossi dinamicamente se possibile);
- Eliminazione in ogni caso solo al passare dei due giorni (per dare tempo a tutti di vedere la proposta);
- Aggiunta di un ✅ sotto la proposta se è passata, o di un ❎ in caso di proposta bocciata;
- Annuncio nel canale Annunci sul fatto che la proposta è passata e che è in fase di ultima approvazione;
- La possibilità di approvare tale proposta attraverso un input (una reaction con un 🟢 per esempio sotto il messaggio in annunci);
- In caso di approvazione, il cambiamento successivo del messaggio negli annunci in "proposta approvata" (o simile);
- L'eliminazione del suddetto messaggio altrimenti.

Parte di questa idea può essere rivista insieme in seguito, ovviamente.

**Comment by Skylake-dev** [comment]
Continuiamo la discussione sulla pull request.
