### ISSUE TITLE
Ruolo Attivo

### ISSUE THREAD

**Issue by cathartyc** [AFLdiscord/AFL-Bot#2]
Il ruolo Attivo deve seguire il regolamento.
- Il contatore va incrementato sse l'utente scrive in un canale valido (tracciato da un file);
- si registra la data di invio del primo messaggio dell'utente;
- alle 00:00 di ogni giorno si effettua un check sul contatore di ciascun membro:
    - se >= 100, si registra la data in questione, si imposta il ruolo attivo e si resetta il contatore;
    - se è passata una settimana dal primo messaggio contato e il contatore è < 100, si resetta il contatore ed eventualmente si rimuove il ruolo Attivo;
    - altrimenti non si deve fare nulla.
- Solo utenti con il ruolo Attivo possono votare in **proposte**, quindi vanno eliminate le reaction di chi non possiede tale ruolo.

**Comment by Skylake-dev** [comment]
Il rinnovo del ruolo attivo come viene gestito?

> alle 00:00 di ogni giorno si effettua un check sul contatore di ciascun membro:
>- se >= 100, si registra la data in questione, si imposta il ruolo attivo e si resetta il contatore;
>- se è passata una settimana dal primo messaggio contato e il contatore è < 100, si resetta il contatore ed eventualmente si rimuove il ruolo Attivo;
>- altrimenti non si deve fare nulla.

Seguendo questa procedura non è chiaro cosa succeda in caso il ruolo sia già stato assegnato.
Esempio:
- oggi scrivo 100 messaggi e a mezzanotte mi viene assegnato il ruolo e azzerato il contatore (fin qua tutto ok)
- domani scrivo altri 100 messaggi ma ho già il ruolo

La domanda a questo punto è: il ruolo viene rinnovato per 7 giorni dal nuovo raggiungimento della soglia (nel caso dell'esempio, scade un giorno dopo rispetto al precedente) oppure vengono aggiunti 7 giorni alla scadenza (nel caso dell'esempio durerebbe 14 giorni in totale dal primo giorno).

Propenderei per la prima opzione (7 giorni dalla data di ogni rinnovo)

**Comment by Skylake-dev** [comment]
Un'altra questione è invece cosa succeda in caso di partecipazione "sparsa". Mi spiego meglio.
Se un utente partecipa poco alle conversazioni non riuscendo a raggiungere i 100 messaggi ogni 7 giorni ogni settimana il conteggio gli viene azzerato. In questo modo stiamo contanto solo i messaggi inviati "a blocchi" di durata 7 giorni invece che i messaggi degli ultimi 7 giorni. 
Caso limite per rendere evidente la problematica (assumiamo di avere i contatori a 0 inizialmente):
- utente X scrive un messaggio il lunedì --> il bot registra come data di inizio conteggio il lunedì
- X non scrive altri messaggi per tutta la settimana fino a domenica dove scrive 98 messaggi (99 in totale, appena sotto la soglia)
- a mezzanotte di domenica il bot controllerebbe i messaggi mandati da X ed essendo < 100 li azzererebbe non assegnado il ruolo, giustamente perchè non ha raggiunto la soglia
- tuttavia il lunedì successivo X scrive altri 2 messaggi --> il bot registra come data di inizio questo giorno e a mezzanotte non assegna il ruolo attivo a X perchè ha solo 2 messaggi. Qua il procedimento non è corretto poichè X ha mandato 100 messaggi negli ultimi 7 giorni (domenica+lunedì successivo) ma non riceve comunque il ruolo perchè il suo conteggio è stato azzerato.

Il problema dunque è che messa così non possiamo tenere conto di una finestra di 7 giorni "mobile" ma possiamo considerare solo blocchi da 7 giorni disgiunti.

Una soluzione potrebbe essere: 
invece di un contatore unico abbiamo 7 contatori, uno per ogni giorno della settimana. L'aggiornamento del contatore avviene seguendo il giorno della settimana e viene sovrascritto la settimana successiva. In questo modo stiamo salvando il numero di messaggi divisi per giorno e possiamo controllare se la somma degli ultimi 7 giorni supera o meno i 100 messaggi. Il problema sarebbe risolto perchè i contatori dei singoli giorni vengono aggiornati ciclicamente, quando inizia una nuova settimana aggiorno solo il lunedì e lascio invariati i contatori degli altri giorni della settimana precedente mantenendo lo "storico" del numero di messaggi mandato.

**Comment by cathartyc** [comment]
>La domanda a questo punto è: il ruolo viene rinnovato per 7 giorni dal nuovo raggiungimento della soglia (nel caso dell'esempio, scade un giorno dopo rispetto al precedente) oppure vengono aggiunti 7 giorni alla scadenza (nel caso dell'esempio durerebbe 14 giorni in totale dal primo giorno)?

Intendevo la prima: se si ottiene il ruolo in giorno 5-02 che scade il 12-02, e si riottiene  il 7, la nuova data sarà il 14-02.

> invece di un contatore unico abbiamo 7 contatori, uno per ogni giorno della settimana.

L'idea proposta è accettabile. A questo punto bisognerà modificare le funzioni di ruolo sommando il contenuto di tutti e 7 i contatori, e le funzioni di reset devono azzerare solo il contatore del giorno in cui avviene il controllo.
