### ISSUE TITLE
Ammissione automatica nuovi membri

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#22]
Accettare automaticamente i nuovi membri che si presentano nel canale richiesta-di-afl per evitare che debbano aspettare l'approvazione esplicita di un moderatore. i moderatori possono comunque controllare successivamente (magari assegnare un ruolo "pending" giusto per avere il colore diverso).

**Comment by cathartyc** [comment]
Una proposta di meccanismo per gestire gli ingressi potrebbe essere questa:

**Modifica della funzione di #richiesta-di-afl**
Il canale diventa un semplice canale di benvenuto/annuncio pubblico, dove l'utente non scrive nulla.

**Spostamento della presentazione in DM**
L'utente viene interrogato in DM su sesso ed età (formato dei campi formalizzabile come nel regolamento, ossia:
`sesso`
`età`
o `sesso, età`, questo dettaglio implementativo può essere ridiscusso in un secondo momento).

**Controllo dei dati inseriti**
Questa parte può essere automatizzabile o meno. Una cosa che possiamo fare per mantenere un controllo manuale, almeno inizialmente, è quello di mandare questi dati ai moderatori, e far decidere a loro se accettarli o meno. Altrimenti il controllo può essere effettuato totalmente dal bot, inserendo semplici controlli di formato (con il formato `sesso, età` ad esempio basta splittare sulla virgola e controllare che il primo campo sia di formato sesso e che l'altro sia un numero. O ancora, un sistema ibrido in cui il bot controlli il formato e il reparto di moderazione controlli la concretezza dei dati (questo per evitare l'ingresso di utenti di 299 anni).

**Annuncio del bot dell'avvenuta iscrizione**
Se i dati sono accettati dal bot, l'utente diventa membro di AFL e _solo_ in quel caso viene annunciata la sua introduzione nel server.

**(Bonus) Presentazione classica**
Possiamo dare ai nuovi utenti la possibilità (o una sorta di dovere morale), di scrivere una breve presentazione, in cui possono dire ad esempio quali siano i propri interessi personali (hobby ecc.) e cosa li abbia spinti ad entrare.
Tutto ciò in un canale a parte, intuibilmente nei canali #extra, o direttamente in bacheca.

Questo sistema propone una soluzione per questa issue e anche per la #23 .
