### ISSUE TITLE
Comando `<4chan`

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#51]
Nuovo comando che prende le immagini migliori da `r/4chan` o `r/greentext` e le posta in un embed.
Pensato per rimpiazzare il comando di Dank Memer che è stato rimosso.

**Comment by cathartyc** [comment]
Dank Memer permette di accedere a quelle funzioni via slash command, quindi non è più necessario. In futuro penseremo a un modo per pullare immagini da alcuni subreddit in maniera autonoma.
