### ISSUE TITLE
Revisione procedura da seguire all'ingresso di un nuovo membro

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#53]
Gestire meglio le varie casistiche possibili (nickname non valido, già preso, presentazione, etc)

**Comment by cathartyc** [comment]
Il bot, all'ingresso di un nuovo membro nel server, potrebbe mandare un messaggio nel canale di presentazione iniziale (ad es.: "Benvenuto su AFL! Presentati usando il comando `/presentation`"
