### ISSUE TITLE
Duplicazione del conteggio del messaggio di un thread

### ISSUE THREAD

**Issue by cathartyc** [AFLdiscord/AFL-Bot#59]
Quando viene creato un thread, il contatore relativo alla categoria del canale incrementa una volta più del necessario.

Questo succede sia quando il thread viene creato a partire da un messaggio in chat, sia quando viene creato indipendentemente.

**Comment by Skylake-dev** [comment]
Il problema è più esteso in quanto ci sono diversi tipi di messaggi che vengono generati da discord e attribuiti all'utente, come ad esempio il pin dei messaggi. Per risolvere la situazione è sufficiente ignorare tutte le tipologie di messaggi che non siano un messaggio standard o una reply
