### ISSUE TITLE
Conteggio voti proposte

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#65]
Qualcosa si è rotto nel conteggio dei voti delle proposte, bisognerà investigare

**Comment by cathartyc** [comment]
Il problema non si è verificato provando le seguenti tipologie di proposte:
- proposta con testo normale;
- proposta con testo ed immagine;
- proposta con testo ed embed del link;
- proposta precedente, dopo aver rimosso manualmente l'embed;
- proposta con testo, embed ed immagine.

In nessuno dei casi visti si è verificato il problema (aggiornamento mancante dei contatori).

Se dovesse ripresentarsi il problema, questa issue verrà riaperta indicando, possibilmente, come riprodurlo.
