### ISSUE TITLE
Post dai subreddit

### ISSUE THREAD

**Issue by Skylake-dev** [AFLdiscord/AFL-Bot#66]
Come precedentemente detto in #51, vorremmo integrare nel bot dei comandi per prendere su richiesta post di tendenza da alcuni subreddit. L'idea generale è la creazione di un'apposita cog per interfacciarsi con le API di reddit e creare un'astrazione che permetta di scegliere dinamicamente i subreddit di interesse.

**Comment by cathartyc** [comment]
Un possibile wrapper per le API di Reddit è [PRAW](https://asyncpraw.readthedocs.io/en/stable), il cui autore consiglia la versione async per impieghi quali quello di un bot di discord.

**Comment by cathartyc** [comment]
Andrebbe anche riportata nel README la procedura per ottenere le chiavi di accesso per le API di reddit

**Comment by cathartyc** [comment]
L'infrastruttura generale è stata implementata in https://github.com/AFLdiscord/AFL-Bot/commit/7306b82b07c4ba58ba977a0af43ebf84cc9a512b

Ci sono le seguenti cose da fare e/o da verificarne la fattibilità:
- [ ] scarto dei messaggi pinnati
- [ ] scarto dei post eliminati (può accadere quando i post vengono eliminati dopo aver generato la cache)
- [ ] supporto a foto
- [ ] supporto a galleria di foto
- [ ] supporto a video
- [ ] supporto a galleria di formati misti
- [ ] comando per gestire i subreddit da cui è possibile caricare dei post

**Comment by cathartyc** [comment]
Potrebbe essere utile gestire un dizionario di alias per i subreddit, in modo da non dover scrivere interamente il nome dei sub più lunghi.

**Comment by cathartyc** [comment]
Il supporto a video è stato rimosso dalla lista delle cose in programma, in quanto le API di Reddit non permettono di ottenerli in maniera sufficientemente semplice.
